apiVersion: apps/v1
kind: Deployment
metadata:
  name: aviator-dashboard
  labels:
    app: aviator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aviator
  template:
    metadata:
      labels:
        app: aviator
        # REMOVED: azure.workload.identity/use: "true"
    spec:
      serviceAccountName: aviator-service-account
      containers:
      - name: aviator-container
        image: aviatoracrjetops01.azurecr.io/aviator-maintenance-app:latest # Use the latest pushed image
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: aviator-service
spec:
  type: LoadBalancer
  selector:
    app: aviator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aviator-service-account
  namespace: default